/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MaRouteImport } from './routes/ma'
import { Route as MesterRouteImport } from './routes/mester'
import { Route as SvendRouteImport } from './routes/svend'
import { Route as KundeSlugRouteImport } from './routes/kunde.$slug'
import { Route as MaIndexRouteImport } from './routes/ma.index'
import { Route as MaSagRouteImport } from './routes/ma.$sag'
import { Route as SagSlugRouteImport } from './routes/sag.$slug'
import { Route as TfTokenRouteImport } from './routes/tf.$token'
import { Route as KundeSlugIndexRouteImport } from './routes/kunde.$slug.index'
import { Route as KundeSlugPunktRouteImport } from './routes/kunde.$slug.$punkt'
import { Route as KundeSlugHaandbogRouteImport } from './routes/kunde.$slug.haandbog'
import { Route as KundeSlugKompletRouteImport } from './routes/kunde.$slug.komplet'
import { Route as MaSagIndexRouteImport } from './routes/ma.$sag.index'
import { Route as MaSagOrdreRouteImport } from './routes/ma.$sag.$ordre'
import { Route as RKindNumberRouteImport } from './routes/r.$kind.$number'
import { Route as SagSlugIndexRouteImport } from './routes/sag.$slug.index'
import { Route as SagSlugAsRouteImport } from './routes/sag.$slug.as'
import { Route as SagSlugErRouteImport } from './routes/sag.$slug.er'
import { Route as SagSlugKsRouteImport } from './routes/sag.$slug.ks'
import { Route as SagSlugSamlingRouteImport } from './routes/sag.$slug.samling'
import { Route as SagSlugTbRouteImport } from './routes/sag.$slug.tb'
import { Route as SagSlugTfRouteImport } from './routes/sag.$slug.tf'
import { Route as SagSlugTodoRouteImport } from './routes/sag.$slug.todo'
import { Route as KundeSlugPunktIndexRouteImport } from './routes/kunde.$slug.$punkt.index'
import { Route as KundeSlugPunktRapportRouteImport } from './routes/kunde.$slug.$punkt.$rapport'
import { Route as MaSagOrdreIndexRouteImport } from './routes/ma.$sag.$ordre.index'
import { Route as MaSagOrdreLinjeRouteImport } from './routes/ma.$sag.$ordre.$linje'
import { Route as MaSagOrdreModtagetRouteImport } from './routes/ma.$sag.$ordre.modtaget'
import { Route as MaSagOrdrePdfRouteImport } from './routes/ma.$sag.$ordre.pdf'
import { Route as SagSlugAsIndexRouteImport } from './routes/sag.$slug.as.index'
import { Route as SagSlugAsNumberRouteImport } from './routes/sag.$slug.as.$number'
import { Route as SagSlugErIndexRouteImport } from './routes/sag.$slug.er.index'
import { Route as SagSlugErNumberRouteImport } from './routes/sag.$slug.er.$number'
import { Route as SagSlugKsIndexRouteImport } from './routes/sag.$slug.ks.index'
import { Route as SagSlugKsNumberRouteImport } from './routes/sag.$slug.ks.$number'
import { Route as SagSlugTbIndexRouteImport } from './routes/sag.$slug.tb.index'
import { Route as SagSlugTbNumberRouteImport } from './routes/sag.$slug.tb.$number'
import { Route as SagSlugTfIndexRouteImport } from './routes/sag.$slug.tf.index'
import { Route as SagSlugTfNumberRouteImport } from './routes/sag.$slug.tf.$number'
import { Route as SagSlugTodoIndexRouteImport } from './routes/sag.$slug.todo.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaRoute = MaRouteImport.update({
  id: '/ma',
  path: '/ma',
  getParentRoute: () => rootRouteImport,
} as any)
const MesterRoute = MesterRouteImport.update({
  id: '/mester',
  path: '/mester',
  getParentRoute: () => rootRouteImport,
} as any)
const SvendRoute = SvendRouteImport.update({
  id: '/svend',
  path: '/svend',
  getParentRoute: () => rootRouteImport,
} as any)
const KundeSlugRoute = KundeSlugRouteImport.update({
  id: '/kunde/$slug',
  path: '/kunde/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MaIndexRoute = MaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaRoute,
} as any)
const MaSagRoute = MaSagRouteImport.update({
  id: '/$sag',
  path: '/$sag',
  getParentRoute: () => MaRoute,
} as any)
const SagSlugRoute = SagSlugRouteImport.update({
  id: '/sag/$slug',
  path: '/sag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TfTokenRoute = TfTokenRouteImport.update({
  id: '/tf/$token',
  path: '/tf/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KundeSlugIndexRoute = KundeSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundeSlugRoute,
} as any)
const KundeSlugPunktRoute = KundeSlugPunktRouteImport.update({
  id: '/$punkt',
  path: '/$punkt',
  getParentRoute: () => KundeSlugRoute,
} as any)
const KundeSlugHaandbogRoute = KundeSlugHaandbogRouteImport.update({
  id: '/haandbog',
  path: '/haandbog',
  getParentRoute: () => KundeSlugRoute,
} as any)
const KundeSlugKompletRoute = KundeSlugKompletRouteImport.update({
  id: '/komplet',
  path: '/komplet',
  getParentRoute: () => KundeSlugRoute,
} as any)
const MaSagIndexRoute = MaSagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaSagRoute,
} as any)
const MaSagOrdreRoute = MaSagOrdreRouteImport.update({
  id: '/$ordre',
  path: '/$ordre',
  getParentRoute: () => MaSagRoute,
} as any)
const RKindNumberRoute = RKindNumberRouteImport.update({
  id: '/r/$kind/$number',
  path: '/r/$kind/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const SagSlugIndexRoute = SagSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugAsRoute = SagSlugAsRouteImport.update({
  id: '/as',
  path: '/as',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugErRoute = SagSlugErRouteImport.update({
  id: '/er',
  path: '/er',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugKsRoute = SagSlugKsRouteImport.update({
  id: '/ks',
  path: '/ks',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugSamlingRoute = SagSlugSamlingRouteImport.update({
  id: '/samling',
  path: '/samling',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugTbRoute = SagSlugTbRouteImport.update({
  id: '/tb',
  path: '/tb',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugTfRoute = SagSlugTfRouteImport.update({
  id: '/tf',
  path: '/tf',
  getParentRoute: () => SagSlugRoute,
} as any)
const SagSlugTodoRoute = SagSlugTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => SagSlugRoute,
} as any)
const KundeSlugPunktIndexRoute = KundeSlugPunktIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KundeSlugPunktRoute,
} as any)
const KundeSlugPunktRapportRoute = KundeSlugPunktRapportRouteImport.update({
  id: '/$rapport',
  path: '/$rapport',
  getParentRoute: () => KundeSlugPunktRoute,
} as any)
const MaSagOrdreIndexRoute = MaSagOrdreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaSagOrdreRoute,
} as any)
const MaSagOrdreLinjeRoute = MaSagOrdreLinjeRouteImport.update({
  id: '/$linje',
  path: '/$linje',
  getParentRoute: () => MaSagOrdreRoute,
} as any)
const MaSagOrdreModtagetRoute = MaSagOrdreModtagetRouteImport.update({
  id: '/modtaget',
  path: '/modtaget',
  getParentRoute: () => MaSagOrdreRoute,
} as any)
const MaSagOrdrePdfRoute = MaSagOrdrePdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => MaSagOrdreRoute,
} as any)
const SagSlugAsIndexRoute = SagSlugAsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugAsRoute,
} as any)
const SagSlugAsNumberRoute = SagSlugAsNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => SagSlugAsRoute,
} as any)
const SagSlugErIndexRoute = SagSlugErIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugErRoute,
} as any)
const SagSlugErNumberRoute = SagSlugErNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => SagSlugErRoute,
} as any)
const SagSlugKsIndexRoute = SagSlugKsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugKsRoute,
} as any)
const SagSlugKsNumberRoute = SagSlugKsNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => SagSlugKsRoute,
} as any)
const SagSlugTbIndexRoute = SagSlugTbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugTbRoute,
} as any)
const SagSlugTbNumberRoute = SagSlugTbNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => SagSlugTbRoute,
} as any)
const SagSlugTfIndexRoute = SagSlugTfIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugTfRoute,
} as any)
const SagSlugTfNumberRoute = SagSlugTfNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => SagSlugTfRoute,
} as any)
const SagSlugTodoIndexRoute = SagSlugTodoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SagSlugTodoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ma': typeof MaRouteWithChildren
  '/mester': typeof MesterRoute
  '/svend': typeof SvendRoute
  '/kunde/$slug': typeof KundeSlugRouteWithChildren
  '/ma/$sag': typeof MaSagRouteWithChildren
  '/sag/$slug': typeof SagSlugRouteWithChildren
  '/tf/$token': typeof TfTokenRoute
  '/ma/': typeof MaIndexRoute
  '/kunde/$slug/$punkt': typeof KundeSlugPunktRouteWithChildren
  '/kunde/$slug/haandbog': typeof KundeSlugHaandbogRoute
  '/kunde/$slug/komplet': typeof KundeSlugKompletRoute
  '/ma/$sag/$ordre': typeof MaSagOrdreRouteWithChildren
  '/r/$kind/$number': typeof RKindNumberRoute
  '/sag/$slug/as': typeof SagSlugAsRouteWithChildren
  '/sag/$slug/er': typeof SagSlugErRouteWithChildren
  '/sag/$slug/ks': typeof SagSlugKsRouteWithChildren
  '/sag/$slug/samling': typeof SagSlugSamlingRoute
  '/sag/$slug/tb': typeof SagSlugTbRouteWithChildren
  '/sag/$slug/tf': typeof SagSlugTfRouteWithChildren
  '/sag/$slug/todo': typeof SagSlugTodoRouteWithChildren
  '/kunde/$slug/': typeof KundeSlugIndexRoute
  '/ma/$sag/': typeof MaSagIndexRoute
  '/sag/$slug/': typeof SagSlugIndexRoute
  '/kunde/$slug/$punkt/$rapport': typeof KundeSlugPunktRapportRoute
  '/ma/$sag/$ordre/$linje': typeof MaSagOrdreLinjeRoute
  '/ma/$sag/$ordre/modtaget': typeof MaSagOrdreModtagetRoute
  '/ma/$sag/$ordre/pdf': typeof MaSagOrdrePdfRoute
  '/sag/$slug/as/$number': typeof SagSlugAsNumberRoute
  '/sag/$slug/er/$number': typeof SagSlugErNumberRoute
  '/sag/$slug/ks/$number': typeof SagSlugKsNumberRoute
  '/sag/$slug/tb/$number': typeof SagSlugTbNumberRoute
  '/sag/$slug/tf/$number': typeof SagSlugTfNumberRoute
  '/kunde/$slug/$punkt/': typeof KundeSlugPunktIndexRoute
  '/ma/$sag/$ordre/': typeof MaSagOrdreIndexRoute
  '/sag/$slug/as/': typeof SagSlugAsIndexRoute
  '/sag/$slug/er/': typeof SagSlugErIndexRoute
  '/sag/$slug/ks/': typeof SagSlugKsIndexRoute
  '/sag/$slug/tb/': typeof SagSlugTbIndexRoute
  '/sag/$slug/tf/': typeof SagSlugTfIndexRoute
  '/sag/$slug/todo/': typeof SagSlugTodoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mester': typeof MesterRoute
  '/svend': typeof SvendRoute
  '/tf/$token': typeof TfTokenRoute
  '/ma': typeof MaIndexRoute
  '/kunde/$slug/haandbog': typeof KundeSlugHaandbogRoute
  '/kunde/$slug/komplet': typeof KundeSlugKompletRoute
  '/r/$kind/$number': typeof RKindNumberRoute
  '/sag/$slug/samling': typeof SagSlugSamlingRoute
  '/kunde/$slug': typeof KundeSlugIndexRoute
  '/ma/$sag': typeof MaSagIndexRoute
  '/sag/$slug': typeof SagSlugIndexRoute
  '/kunde/$slug/$punkt/$rapport': typeof KundeSlugPunktRapportRoute
  '/ma/$sag/$ordre/$linje': typeof MaSagOrdreLinjeRoute
  '/ma/$sag/$ordre/modtaget': typeof MaSagOrdreModtagetRoute
  '/ma/$sag/$ordre/pdf': typeof MaSagOrdrePdfRoute
  '/sag/$slug/as/$number': typeof SagSlugAsNumberRoute
  '/sag/$slug/er/$number': typeof SagSlugErNumberRoute
  '/sag/$slug/ks/$number': typeof SagSlugKsNumberRoute
  '/sag/$slug/tb/$number': typeof SagSlugTbNumberRoute
  '/sag/$slug/tf/$number': typeof SagSlugTfNumberRoute
  '/kunde/$slug/$punkt': typeof KundeSlugPunktIndexRoute
  '/ma/$sag/$ordre': typeof MaSagOrdreIndexRoute
  '/sag/$slug/as': typeof SagSlugAsIndexRoute
  '/sag/$slug/er': typeof SagSlugErIndexRoute
  '/sag/$slug/ks': typeof SagSlugKsIndexRoute
  '/sag/$slug/tb': typeof SagSlugTbIndexRoute
  '/sag/$slug/tf': typeof SagSlugTfIndexRoute
  '/sag/$slug/todo': typeof SagSlugTodoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ma': typeof MaRouteWithChildren
  '/mester': typeof MesterRoute
  '/svend': typeof SvendRoute
  '/kunde/$slug': typeof KundeSlugRouteWithChildren
  '/ma/$sag': typeof MaSagRouteWithChildren
  '/sag/$slug': typeof SagSlugRouteWithChildren
  '/tf/$token': typeof TfTokenRoute
  '/ma/': typeof MaIndexRoute
  '/kunde/$slug/$punkt': typeof KundeSlugPunktRouteWithChildren
  '/kunde/$slug/haandbog': typeof KundeSlugHaandbogRoute
  '/kunde/$slug/komplet': typeof KundeSlugKompletRoute
  '/ma/$sag/$ordre': typeof MaSagOrdreRouteWithChildren
  '/r/$kind/$number': typeof RKindNumberRoute
  '/sag/$slug/as': typeof SagSlugAsRouteWithChildren
  '/sag/$slug/er': typeof SagSlugErRouteWithChildren
  '/sag/$slug/ks': typeof SagSlugKsRouteWithChildren
  '/sag/$slug/samling': typeof SagSlugSamlingRoute
  '/sag/$slug/tb': typeof SagSlugTbRouteWithChildren
  '/sag/$slug/tf': typeof SagSlugTfRouteWithChildren
  '/sag/$slug/todo': typeof SagSlugTodoRouteWithChildren
  '/kunde/$slug/': typeof KundeSlugIndexRoute
  '/ma/$sag/': typeof MaSagIndexRoute
  '/sag/$slug/': typeof SagSlugIndexRoute
  '/kunde/$slug/$punkt/$rapport': typeof KundeSlugPunktRapportRoute
  '/ma/$sag/$ordre/$linje': typeof MaSagOrdreLinjeRoute
  '/ma/$sag/$ordre/modtaget': typeof MaSagOrdreModtagetRoute
  '/ma/$sag/$ordre/pdf': typeof MaSagOrdrePdfRoute
  '/sag/$slug/as/$number': typeof SagSlugAsNumberRoute
  '/sag/$slug/er/$number': typeof SagSlugErNumberRoute
  '/sag/$slug/ks/$number': typeof SagSlugKsNumberRoute
  '/sag/$slug/tb/$number': typeof SagSlugTbNumberRoute
  '/sag/$slug/tf/$number': typeof SagSlugTfNumberRoute
  '/kunde/$slug/$punkt/': typeof KundeSlugPunktIndexRoute
  '/ma/$sag/$ordre/': typeof MaSagOrdreIndexRoute
  '/sag/$slug/as/': typeof SagSlugAsIndexRoute
  '/sag/$slug/er/': typeof SagSlugErIndexRoute
  '/sag/$slug/ks/': typeof SagSlugKsIndexRoute
  '/sag/$slug/tb/': typeof SagSlugTbIndexRoute
  '/sag/$slug/tf/': typeof SagSlugTfIndexRoute
  '/sag/$slug/todo/': typeof SagSlugTodoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ma'
    | '/mester'
    | '/svend'
    | '/kunde/$slug'
    | '/ma/$sag'
    | '/sag/$slug'
    | '/tf/$token'
    | '/ma/'
    | '/kunde/$slug/$punkt'
    | '/kunde/$slug/haandbog'
    | '/kunde/$slug/komplet'
    | '/ma/$sag/$ordre'
    | '/r/$kind/$number'
    | '/sag/$slug/as'
    | '/sag/$slug/er'
    | '/sag/$slug/ks'
    | '/sag/$slug/samling'
    | '/sag/$slug/tb'
    | '/sag/$slug/tf'
    | '/sag/$slug/todo'
    | '/kunde/$slug/'
    | '/ma/$sag/'
    | '/sag/$slug/'
    | '/kunde/$slug/$punkt/$rapport'
    | '/ma/$sag/$ordre/$linje'
    | '/ma/$sag/$ordre/modtaget'
    | '/ma/$sag/$ordre/pdf'
    | '/sag/$slug/as/$number'
    | '/sag/$slug/er/$number'
    | '/sag/$slug/ks/$number'
    | '/sag/$slug/tb/$number'
    | '/sag/$slug/tf/$number'
    | '/kunde/$slug/$punkt/'
    | '/ma/$sag/$ordre/'
    | '/sag/$slug/as/'
    | '/sag/$slug/er/'
    | '/sag/$slug/ks/'
    | '/sag/$slug/tb/'
    | '/sag/$slug/tf/'
    | '/sag/$slug/todo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mester'
    | '/svend'
    | '/tf/$token'
    | '/ma'
    | '/kunde/$slug/haandbog'
    | '/kunde/$slug/komplet'
    | '/r/$kind/$number'
    | '/sag/$slug/samling'
    | '/kunde/$slug'
    | '/ma/$sag'
    | '/sag/$slug'
    | '/kunde/$slug/$punkt/$rapport'
    | '/ma/$sag/$ordre/$linje'
    | '/ma/$sag/$ordre/modtaget'
    | '/ma/$sag/$ordre/pdf'
    | '/sag/$slug/as/$number'
    | '/sag/$slug/er/$number'
    | '/sag/$slug/ks/$number'
    | '/sag/$slug/tb/$number'
    | '/sag/$slug/tf/$number'
    | '/kunde/$slug/$punkt'
    | '/ma/$sag/$ordre'
    | '/sag/$slug/as'
    | '/sag/$slug/er'
    | '/sag/$slug/ks'
    | '/sag/$slug/tb'
    | '/sag/$slug/tf'
    | '/sag/$slug/todo'
  id:
    | '__root__'
    | '/'
    | '/ma'
    | '/mester'
    | '/svend'
    | '/kunde/$slug'
    | '/ma/$sag'
    | '/sag/$slug'
    | '/tf/$token'
    | '/ma/'
    | '/kunde/$slug/$punkt'
    | '/kunde/$slug/haandbog'
    | '/kunde/$slug/komplet'
    | '/ma/$sag/$ordre'
    | '/r/$kind/$number'
    | '/sag/$slug/as'
    | '/sag/$slug/er'
    | '/sag/$slug/ks'
    | '/sag/$slug/samling'
    | '/sag/$slug/tb'
    | '/sag/$slug/tf'
    | '/sag/$slug/todo'
    | '/kunde/$slug/'
    | '/ma/$sag/'
    | '/sag/$slug/'
    | '/kunde/$slug/$punkt/$rapport'
    | '/ma/$sag/$ordre/$linje'
    | '/ma/$sag/$ordre/modtaget'
    | '/ma/$sag/$ordre/pdf'
    | '/sag/$slug/as/$number'
    | '/sag/$slug/er/$number'
    | '/sag/$slug/ks/$number'
    | '/sag/$slug/tb/$number'
    | '/sag/$slug/tf/$number'
    | '/kunde/$slug/$punkt/'
    | '/ma/$sag/$ordre/'
    | '/sag/$slug/as/'
    | '/sag/$slug/er/'
    | '/sag/$slug/ks/'
    | '/sag/$slug/tb/'
    | '/sag/$slug/tf/'
    | '/sag/$slug/todo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaRoute: typeof MaRouteWithChildren
  MesterRoute: typeof MesterRoute
  SvendRoute: typeof SvendRoute
  KundeSlugRoute: typeof KundeSlugRouteWithChildren
  SagSlugRoute: typeof SagSlugRouteWithChildren
  TfTokenRoute: typeof TfTokenRoute
  RKindNumberRoute: typeof RKindNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ma': {
      id: '/ma'
      path: '/ma'
      fullPath: '/ma'
      preLoaderRoute: typeof MaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mester': {
      id: '/mester'
      path: '/mester'
      fullPath: '/mester'
      preLoaderRoute: typeof MesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svend': {
      id: '/svend'
      path: '/svend'
      fullPath: '/svend'
      preLoaderRoute: typeof SvendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunde/$slug': {
      id: '/kunde/$slug'
      path: '/kunde/$slug'
      fullPath: '/kunde/$slug'
      preLoaderRoute: typeof KundeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ma/': {
      id: '/ma/'
      path: '/'
      fullPath: '/ma/'
      preLoaderRoute: typeof MaIndexRouteImport
      parentRoute: typeof MaRoute
    }
    '/ma/$sag': {
      id: '/ma/$sag'
      path: '/$sag'
      fullPath: '/ma/$sag'
      preLoaderRoute: typeof MaSagRouteImport
      parentRoute: typeof MaRoute
    }
    '/sag/$slug': {
      id: '/sag/$slug'
      path: '/sag/$slug'
      fullPath: '/sag/$slug'
      preLoaderRoute: typeof SagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tf/$token': {
      id: '/tf/$token'
      path: '/tf/$token'
      fullPath: '/tf/$token'
      preLoaderRoute: typeof TfTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunde/$slug/': {
      id: '/kunde/$slug/'
      path: '/'
      fullPath: '/kunde/$slug/'
      preLoaderRoute: typeof KundeSlugIndexRouteImport
      parentRoute: typeof KundeSlugRoute
    }
    '/kunde/$slug/$punkt': {
      id: '/kunde/$slug/$punkt'
      path: '/$punkt'
      fullPath: '/kunde/$slug/$punkt'
      preLoaderRoute: typeof KundeSlugPunktRouteImport
      parentRoute: typeof KundeSlugRoute
    }
    '/kunde/$slug/haandbog': {
      id: '/kunde/$slug/haandbog'
      path: '/haandbog'
      fullPath: '/kunde/$slug/haandbog'
      preLoaderRoute: typeof KundeSlugHaandbogRouteImport
      parentRoute: typeof KundeSlugRoute
    }
    '/kunde/$slug/komplet': {
      id: '/kunde/$slug/komplet'
      path: '/komplet'
      fullPath: '/kunde/$slug/komplet'
      preLoaderRoute: typeof KundeSlugKompletRouteImport
      parentRoute: typeof KundeSlugRoute
    }
    '/ma/$sag/': {
      id: '/ma/$sag/'
      path: '/'
      fullPath: '/ma/$sag/'
      preLoaderRoute: typeof MaSagIndexRouteImport
      parentRoute: typeof MaSagRoute
    }
    '/ma/$sag/$ordre': {
      id: '/ma/$sag/$ordre'
      path: '/$ordre'
      fullPath: '/ma/$sag/$ordre'
      preLoaderRoute: typeof MaSagOrdreRouteImport
      parentRoute: typeof MaSagRoute
    }
    '/r/$kind/$number': {
      id: '/r/$kind/$number'
      path: '/r/$kind/$number'
      fullPath: '/r/$kind/$number'
      preLoaderRoute: typeof RKindNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sag/$slug/': {
      id: '/sag/$slug/'
      path: '/'
      fullPath: '/sag/$slug/'
      preLoaderRoute: typeof SagSlugIndexRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/as': {
      id: '/sag/$slug/as'
      path: '/as'
      fullPath: '/sag/$slug/as'
      preLoaderRoute: typeof SagSlugAsRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/er': {
      id: '/sag/$slug/er'
      path: '/er'
      fullPath: '/sag/$slug/er'
      preLoaderRoute: typeof SagSlugErRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/ks': {
      id: '/sag/$slug/ks'
      path: '/ks'
      fullPath: '/sag/$slug/ks'
      preLoaderRoute: typeof SagSlugKsRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/samling': {
      id: '/sag/$slug/samling'
      path: '/samling'
      fullPath: '/sag/$slug/samling'
      preLoaderRoute: typeof SagSlugSamlingRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/tb': {
      id: '/sag/$slug/tb'
      path: '/tb'
      fullPath: '/sag/$slug/tb'
      preLoaderRoute: typeof SagSlugTbRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/tf': {
      id: '/sag/$slug/tf'
      path: '/tf'
      fullPath: '/sag/$slug/tf'
      preLoaderRoute: typeof SagSlugTfRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/sag/$slug/todo': {
      id: '/sag/$slug/todo'
      path: '/todo'
      fullPath: '/sag/$slug/todo'
      preLoaderRoute: typeof SagSlugTodoRouteImport
      parentRoute: typeof SagSlugRoute
    }
    '/kunde/$slug/$punkt/': {
      id: '/kunde/$slug/$punkt/'
      path: '/'
      fullPath: '/kunde/$slug/$punkt/'
      preLoaderRoute: typeof KundeSlugPunktIndexRouteImport
      parentRoute: typeof KundeSlugPunktRoute
    }
    '/kunde/$slug/$punkt/$rapport': {
      id: '/kunde/$slug/$punkt/$rapport'
      path: '/$rapport'
      fullPath: '/kunde/$slug/$punkt/$rapport'
      preLoaderRoute: typeof KundeSlugPunktRapportRouteImport
      parentRoute: typeof KundeSlugPunktRoute
    }
    '/ma/$sag/$ordre/': {
      id: '/ma/$sag/$ordre/'
      path: '/'
      fullPath: '/ma/$sag/$ordre/'
      preLoaderRoute: typeof MaSagOrdreIndexRouteImport
      parentRoute: typeof MaSagOrdreRoute
    }
    '/ma/$sag/$ordre/$linje': {
      id: '/ma/$sag/$ordre/$linje'
      path: '/$linje'
      fullPath: '/ma/$sag/$ordre/$linje'
      preLoaderRoute: typeof MaSagOrdreLinjeRouteImport
      parentRoute: typeof MaSagOrdreRoute
    }
    '/ma/$sag/$ordre/modtaget': {
      id: '/ma/$sag/$ordre/modtaget'
      path: '/modtaget'
      fullPath: '/ma/$sag/$ordre/modtaget'
      preLoaderRoute: typeof MaSagOrdreModtagetRouteImport
      parentRoute: typeof MaSagOrdreRoute
    }
    '/ma/$sag/$ordre/pdf': {
      id: '/ma/$sag/$ordre/pdf'
      path: '/pdf'
      fullPath: '/ma/$sag/$ordre/pdf'
      preLoaderRoute: typeof MaSagOrdrePdfRouteImport
      parentRoute: typeof MaSagOrdreRoute
    }
    '/sag/$slug/as/': {
      id: '/sag/$slug/as/'
      path: '/'
      fullPath: '/sag/$slug/as/'
      preLoaderRoute: typeof SagSlugAsIndexRouteImport
      parentRoute: typeof SagSlugAsRoute
    }
    '/sag/$slug/as/$number': {
      id: '/sag/$slug/as/$number'
      path: '/$number'
      fullPath: '/sag/$slug/as/$number'
      preLoaderRoute: typeof SagSlugAsNumberRouteImport
      parentRoute: typeof SagSlugAsRoute
    }
    '/sag/$slug/er/': {
      id: '/sag/$slug/er/'
      path: '/'
      fullPath: '/sag/$slug/er/'
      preLoaderRoute: typeof SagSlugErIndexRouteImport
      parentRoute: typeof SagSlugErRoute
    }
    '/sag/$slug/er/$number': {
      id: '/sag/$slug/er/$number'
      path: '/$number'
      fullPath: '/sag/$slug/er/$number'
      preLoaderRoute: typeof SagSlugErNumberRouteImport
      parentRoute: typeof SagSlugErRoute
    }
    '/sag/$slug/ks/': {
      id: '/sag/$slug/ks/'
      path: '/'
      fullPath: '/sag/$slug/ks/'
      preLoaderRoute: typeof SagSlugKsIndexRouteImport
      parentRoute: typeof SagSlugKsRoute
    }
    '/sag/$slug/ks/$number': {
      id: '/sag/$slug/ks/$number'
      path: '/$number'
      fullPath: '/sag/$slug/ks/$number'
      preLoaderRoute: typeof SagSlugKsNumberRouteImport
      parentRoute: typeof SagSlugKsRoute
    }
    '/sag/$slug/tb/': {
      id: '/sag/$slug/tb/'
      path: '/'
      fullPath: '/sag/$slug/tb/'
      preLoaderRoute: typeof SagSlugTbIndexRouteImport
      parentRoute: typeof SagSlugTbRoute
    }
    '/sag/$slug/tb/$number': {
      id: '/sag/$slug/tb/$number'
      path: '/$number'
      fullPath: '/sag/$slug/tb/$number'
      preLoaderRoute: typeof SagSlugTbNumberRouteImport
      parentRoute: typeof SagSlugTbRoute
    }
    '/sag/$slug/tf/': {
      id: '/sag/$slug/tf/'
      path: '/'
      fullPath: '/sag/$slug/tf/'
      preLoaderRoute: typeof SagSlugTfIndexRouteImport
      parentRoute: typeof SagSlugTfRoute
    }
    '/sag/$slug/tf/$number': {
      id: '/sag/$slug/tf/$number'
      path: '/$number'
      fullPath: '/sag/$slug/tf/$number'
      preLoaderRoute: typeof SagSlugTfNumberRouteImport
      parentRoute: typeof SagSlugTfRoute
    }
    '/sag/$slug/todo/': {
      id: '/sag/$slug/todo/'
      path: '/'
      fullPath: '/sag/$slug/todo/'
      preLoaderRoute: typeof SagSlugTodoIndexRouteImport
      parentRoute: typeof SagSlugTodoRoute
    }
  }
}

interface MaSagOrdreRouteChildren {
  MaSagOrdreLinjeRoute: typeof MaSagOrdreLinjeRoute
  MaSagOrdreModtagetRoute: typeof MaSagOrdreModtagetRoute
  MaSagOrdrePdfRoute: typeof MaSagOrdrePdfRoute
  MaSagOrdreIndexRoute: typeof MaSagOrdreIndexRoute
}

const MaSagOrdreRouteChildren: MaSagOrdreRouteChildren = {
  MaSagOrdreLinjeRoute: MaSagOrdreLinjeRoute,
  MaSagOrdreModtagetRoute: MaSagOrdreModtagetRoute,
  MaSagOrdrePdfRoute: MaSagOrdrePdfRoute,
  MaSagOrdreIndexRoute: MaSagOrdreIndexRoute,
}

const MaSagOrdreRouteWithChildren = MaSagOrdreRoute._addFileChildren(
  MaSagOrdreRouteChildren,
)

interface MaSagRouteChildren {
  MaSagOrdreRoute: typeof MaSagOrdreRouteWithChildren
  MaSagIndexRoute: typeof MaSagIndexRoute
}

const MaSagRouteChildren: MaSagRouteChildren = {
  MaSagOrdreRoute: MaSagOrdreRouteWithChildren,
  MaSagIndexRoute: MaSagIndexRoute,
}

const MaSagRouteWithChildren = MaSagRoute._addFileChildren(MaSagRouteChildren)

interface MaRouteChildren {
  MaSagRoute: typeof MaSagRouteWithChildren
  MaIndexRoute: typeof MaIndexRoute
}

const MaRouteChildren: MaRouteChildren = {
  MaSagRoute: MaSagRouteWithChildren,
  MaIndexRoute: MaIndexRoute,
}

const MaRouteWithChildren = MaRoute._addFileChildren(MaRouteChildren)

interface KundeSlugPunktRouteChildren {
  KundeSlugPunktRapportRoute: typeof KundeSlugPunktRapportRoute
  KundeSlugPunktIndexRoute: typeof KundeSlugPunktIndexRoute
}

const KundeSlugPunktRouteChildren: KundeSlugPunktRouteChildren = {
  KundeSlugPunktRapportRoute: KundeSlugPunktRapportRoute,
  KundeSlugPunktIndexRoute: KundeSlugPunktIndexRoute,
}

const KundeSlugPunktRouteWithChildren = KundeSlugPunktRoute._addFileChildren(
  KundeSlugPunktRouteChildren,
)

interface KundeSlugRouteChildren {
  KundeSlugPunktRoute: typeof KundeSlugPunktRouteWithChildren
  KundeSlugHaandbogRoute: typeof KundeSlugHaandbogRoute
  KundeSlugKompletRoute: typeof KundeSlugKompletRoute
  KundeSlugIndexRoute: typeof KundeSlugIndexRoute
}

const KundeSlugRouteChildren: KundeSlugRouteChildren = {
  KundeSlugPunktRoute: KundeSlugPunktRouteWithChildren,
  KundeSlugHaandbogRoute: KundeSlugHaandbogRoute,
  KundeSlugKompletRoute: KundeSlugKompletRoute,
  KundeSlugIndexRoute: KundeSlugIndexRoute,
}

const KundeSlugRouteWithChildren = KundeSlugRoute._addFileChildren(
  KundeSlugRouteChildren,
)

interface SagSlugAsRouteChildren {
  SagSlugAsNumberRoute: typeof SagSlugAsNumberRoute
  SagSlugAsIndexRoute: typeof SagSlugAsIndexRoute
}

const SagSlugAsRouteChildren: SagSlugAsRouteChildren = {
  SagSlugAsNumberRoute: SagSlugAsNumberRoute,
  SagSlugAsIndexRoute: SagSlugAsIndexRoute,
}

const SagSlugAsRouteWithChildren = SagSlugAsRoute._addFileChildren(
  SagSlugAsRouteChildren,
)

interface SagSlugErRouteChildren {
  SagSlugErNumberRoute: typeof SagSlugErNumberRoute
  SagSlugErIndexRoute: typeof SagSlugErIndexRoute
}

const SagSlugErRouteChildren: SagSlugErRouteChildren = {
  SagSlugErNumberRoute: SagSlugErNumberRoute,
  SagSlugErIndexRoute: SagSlugErIndexRoute,
}

const SagSlugErRouteWithChildren = SagSlugErRoute._addFileChildren(
  SagSlugErRouteChildren,
)

interface SagSlugKsRouteChildren {
  SagSlugKsNumberRoute: typeof SagSlugKsNumberRoute
  SagSlugKsIndexRoute: typeof SagSlugKsIndexRoute
}

const SagSlugKsRouteChildren: SagSlugKsRouteChildren = {
  SagSlugKsNumberRoute: SagSlugKsNumberRoute,
  SagSlugKsIndexRoute: SagSlugKsIndexRoute,
}

const SagSlugKsRouteWithChildren = SagSlugKsRoute._addFileChildren(
  SagSlugKsRouteChildren,
)

interface SagSlugTbRouteChildren {
  SagSlugTbNumberRoute: typeof SagSlugTbNumberRoute
  SagSlugTbIndexRoute: typeof SagSlugTbIndexRoute
}

const SagSlugTbRouteChildren: SagSlugTbRouteChildren = {
  SagSlugTbNumberRoute: SagSlugTbNumberRoute,
  SagSlugTbIndexRoute: SagSlugTbIndexRoute,
}

const SagSlugTbRouteWithChildren = SagSlugTbRoute._addFileChildren(
  SagSlugTbRouteChildren,
)

interface SagSlugTfRouteChildren {
  SagSlugTfNumberRoute: typeof SagSlugTfNumberRoute
  SagSlugTfIndexRoute: typeof SagSlugTfIndexRoute
}

const SagSlugTfRouteChildren: SagSlugTfRouteChildren = {
  SagSlugTfNumberRoute: SagSlugTfNumberRoute,
  SagSlugTfIndexRoute: SagSlugTfIndexRoute,
}

const SagSlugTfRouteWithChildren = SagSlugTfRoute._addFileChildren(
  SagSlugTfRouteChildren,
)

interface SagSlugTodoRouteChildren {
  SagSlugTodoIndexRoute: typeof SagSlugTodoIndexRoute
}

const SagSlugTodoRouteChildren: SagSlugTodoRouteChildren = {
  SagSlugTodoIndexRoute: SagSlugTodoIndexRoute,
}

const SagSlugTodoRouteWithChildren = SagSlugTodoRoute._addFileChildren(
  SagSlugTodoRouteChildren,
)

interface SagSlugRouteChildren {
  SagSlugAsRoute: typeof SagSlugAsRouteWithChildren
  SagSlugErRoute: typeof SagSlugErRouteWithChildren
  SagSlugKsRoute: typeof SagSlugKsRouteWithChildren
  SagSlugSamlingRoute: typeof SagSlugSamlingRoute
  SagSlugTbRoute: typeof SagSlugTbRouteWithChildren
  SagSlugTfRoute: typeof SagSlugTfRouteWithChildren
  SagSlugTodoRoute: typeof SagSlugTodoRouteWithChildren
  SagSlugIndexRoute: typeof SagSlugIndexRoute
}

const SagSlugRouteChildren: SagSlugRouteChildren = {
  SagSlugAsRoute: SagSlugAsRouteWithChildren,
  SagSlugErRoute: SagSlugErRouteWithChildren,
  SagSlugKsRoute: SagSlugKsRouteWithChildren,
  SagSlugSamlingRoute: SagSlugSamlingRoute,
  SagSlugTbRoute: SagSlugTbRouteWithChildren,
  SagSlugTfRoute: SagSlugTfRouteWithChildren,
  SagSlugTodoRoute: SagSlugTodoRouteWithChildren,
  SagSlugIndexRoute: SagSlugIndexRoute,
}

const SagSlugRouteWithChildren =
  SagSlugRoute._addFileChildren(SagSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaRoute: MaRouteWithChildren,
  MesterRoute: MesterRoute,
  SvendRoute: SvendRoute,
  KundeSlugRoute: KundeSlugRouteWithChildren,
  SagSlugRoute: SagSlugRouteWithChildren,
  TfTokenRoute: TfTokenRoute,
  RKindNumberRoute: RKindNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
